import javax.swing.*;

public class Tabela {
    private JTabbedPane TabbedPanel;
    private JPanel GrupoA;
    private JPanel GrupoB;
    private JPanel GrupoC;
    private JPanel GrupoD;
    private JPanel GrupoE;
    private JPanel GrupoF;
    private JPanel GrupoG;
    private JPanel GrupoH;
    private JTextField CatarTextFieldXEquador;
    private JLabel CatarLabel;
    private JTextField EquadorTextFieldXCatar;
    private JLabel VLabelCatarxEquador;
    private JLabel EquadorLabelXCatar;
    private JLabel SenegalLabelXHolanda;
    private JTextField SenegalTextFieldXHolanda;
    private JLabel VLabelSenegalxHolanda;
    private JTextField HolandaTextFieldXSenegal;
    private JLabel HolandaLabelXSenegal;
    private JTextField CatarTextFieldXSenegal;
    private JLabel VLabelCatarxSenegal;
    private JTextField SenegalTextFieldXCatar;
    private JLabel CatarLabelXSenegal;
    private JLabel SenegalLabelXCatar;
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;
    private JTextField textField4;
    private JTextField textField5;
    private JTextField textField6;
    private JTextField textField7;
    private JTextField textField8;
    private JTextField textField9;
    private JTextField textField10;
    private JTextField textField11;
    private JTextField textField12;
    private JTextField textField13;
    private JTextField textField14;
    private JTextField textField15;
    private JTextField textField16;
    private JTextField textField17;
    private JTextField textField18;
    private JTextField textField19;
    private JTextField textField20;
    private JTextField textField21;
    private JTextField textField22;
    private JTextField textField23;
    private JTextField textField24;
    private JTextField textField25;
    private JTextField textField26;
    private JTextField textField27;
    private JTextField textField28;
    private JTextField textField29;
    private JTextField textField30;
    private JTextField textField31;
    private JTextField textField32;
    private JTextField textField33;
    private JTextField textField34;
    private JTextField textField35;
    private JTextField textField36;
    private JTextField textField37;
    private JTextField textField38;
    private JTextField textField39;
    private JTextField textField40;
    private JTextField textField41;
    private JTextField textField42;
    private JTextField textField43;
    private JTextField textField44;
    private JTextField textField45;
    private JTextField textField46;
    private JTextField textField47;
    private JTextField textField48;
    private JTextField textField49;
    private JTextField textField50;
    private JTextField textField51;
    private JTextField textField52;
    private JTextField textField53;
    private JTextField textField54;
    private JTextField textField55;
    private JTextField textField56;
    private JTextField textField57;
    private JTextField textField58;
    private JTextField textField59;
    private JTextField textField60;
    private JTextField textField61;
    private JTextField textField62;
    private JTextField textField63;
    private JTextField textField64;
    private JTextField textField65;
    private JTextField textField66;
    private JTextField textField67;
    private JTextField textField68;
    private JTextField textField69;
    private JTextField textField70;
    private JTextField textField71;
    private JTextField textField72;
    private JTextField textField73;
    private JTextField textField74;
    private JTextField textField75;
    private JTextField textField76;
    private JTextField textField77;
    private JTextField textField78;
    private JTextField textField79;
    private JTextField textField80;
    private JTextField textField81;
    private JTextField textField82;
    private JTextField textField83;
    private JTextField textField84;
    private JTextField textField85;
    private JTextField textField86;
    private JTextField textField87;
    private JTextField textField88;
    private JTextField textField89;
    private JTextField textField90;

    public static void main(String[] args) {

        JFrame frame = new JFrame("Tabela");

        frame.setContentPane(new Tabela().TabbedPanel);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.setVisible(true);

    }

}
