import javax.swing.*;

public class Tabela {
    private JTabbedPane TabbedPanel;
    private JPanel GrupoA;
    private JPanel GrupoB;
    private JPanel GrupoC;
    private JPanel GrupoD;
    private JPanel GrupoE;
    private JPanel GrupoF;
    private JPanel GrupoG;
    private JPanel GrupoH;
    private JTextField CatarGolsXEquador;
    private JTextField EquadorGolsXCatar;
    private JTextField SenegalGolsXHolanda;
    private JTextField HolandaGolsXSenegal;
    private JTextField CatarGolsXSenegal;
    private JTextField SenegalGolsXCatar;
    private JTextField HolandaGolsXEquador;
    private JTextField EquadorGolsXHolanda;
    private JTextField EquadorGolsXSenegal;
    private JTextField SenegalGolsXEquador;
    private JTextField HolandaGolsXCatar;

    private JTextField[] GrupoATexts = new JTextField[]{CatarGolsXEquador, EquadorGolsXCatar, SenegalGolsXHolanda, HolandaGolsXSenegal, CatarGolsXSenegal, SenegalGolsXCatar, HolandaGolsXEquador, EquadorGolsXHolanda, EquadorGolsXSenegal, SenegalGolsXEquador, HolandaGolsXCatar};

    private JTextField CatarGolsXHolanda;
    private JTextField InglaterraGolsXIra;
    private JTextField IraGolsXInglaterra;
    private JTextField GalesGolsXEstadosUnidos;
    private JTextField EstadosUnidosGolsXGales;
    private JTextField GalesGolsXIra;
    private JTextField IraGolsXGales;
    private JTextField InglaterraGolsXEstadosUnidos;
    private JTextField EstadosUnidosGolsXInglaterra;
    private JTextField IraGolsXEstadosUnidos;
    private JTextField EstadosUnidosGolsXIra;
    private JTextField GalesGolsXInglaterra;
    private JTextField InglaterraGolsXGales;

    private JTextField[] GrupoBTexts = new JTextField[]{CatarGolsXHolanda, InglaterraGolsXIra, IraGolsXInglaterra, GalesGolsXEstadosUnidos, EstadosUnidosGolsXGales, GalesGolsXIra, IraGolsXGales, InglaterraGolsXEstadosUnidos, EstadosUnidosGolsXInglaterra, IraGolsXEstadosUnidos, EstadosUnidosGolsXIra, GalesGolsXInglaterra, InglaterraGolsXGales};

    private JTextField ArgentinaGolsXArabia;
    private JTextField ArabiaGolsXArgentina;
    private JTextField MexicoGolsXPolonia;
    private JTextField PoloniaGolsXMexico;
    private JTextField PoloniaGolsXArabia;
    private JTextField ArabiaGolsXPolonia;
    private JTextField ArgentinaGolsXMexico;
    private JTextField MexicoGolsXArgentina;
    private JTextField PoloniaGolsXArgentina;
    private JTextField ArgentinaGolsXPolonia;
    private JTextField ArabiaGolsXMexico;
    private JTextField MexicoGolsXArabia;

    private JTextField[] GrupoCTexts = new JTextField[]{ArgentinaGolsXArabia, ArabiaGolsXArgentina, MexicoGolsXPolonia, PoloniaGolsXMexico, PoloniaGolsXArabia, ArabiaGolsXPolonia, ArgentinaGolsXMexico, MexicoGolsXArgentina, PoloniaGolsXArgentina, ArgentinaGolsXPolonia, ArabiaGolsXMexico, MexicoGolsXArabia};

    private JTextField AlemanhaGolsXJapao;
    private JTextField JapaoGolsXAlemanha;
    private JTextField EspanhaGolsXCostaRica;
    private JTextField CostaRicaGolsXEspanha;
    private JTextField JapaoGolsXCostaRica;
    private JTextField CostaRicaGolsXJapao;
    private JTextField EspanhaGolsXAlemanha;
    private JTextField AlemanhaGolsXEspanha;
    private JTextField JapaoGolsXEspanha;
    private JTextField EspanhaGolsXJapao;
    private JTextField CostaRicaGolsXAlemanha;
    private JTextField AlemanhaGolsXCostaRica;

    private JTextField[] GrupoETexts = new JTextField[]{AlemanhaGolsXJapao, JapaoGolsXAlemanha, EspanhaGolsXCostaRica, CostaRicaGolsXEspanha, JapaoGolsXCostaRica, CostaRicaGolsXJapao, EspanhaGolsXAlemanha, AlemanhaGolsXEspanha, JapaoGolsXEspanha, EspanhaGolsXJapao, CostaRicaGolsXAlemanha, AlemanhaGolsXCostaRica};

    private JTextField MarrocosGolsXCroacia;
    private JTextField CroaciaGolsXMarrocos;
    private JTextField BelgicaGolsXCanada;
    private JTextField CanadaGolsXBelgica;
    private JTextField BelgicaGolsXMarrocos;
    private JTextField MarrocosGolsXBelgica;
    private JTextField CroaciaGolsXCanada;
    private JTextField CanadaGolsXCroacia;
    private JTextField CanadaGolsXMarrocos;
    private JTextField MarrocosGolsXCanada;
    private JTextField CroaciaGolsXBelgica;
    private JTextField BelgicaGolsXCroacia;

    JTextField[] GrupoFTexts = new JTextField[]{MarrocosGolsXCroacia, CroaciaGolsXMarrocos, BelgicaGolsXCanada, CanadaGolsXBelgica, BelgicaGolsXMarrocos, MarrocosGolsXBelgica, CroaciaGolsXCanada, CanadaGolsXCroacia, CanadaGolsXMarrocos, MarrocosGolsXCanada, CroaciaGolsXBelgica, BelgicaGolsXCroacia};

    private JTextField SuicaGolsXCamaroes;
    private JTextField CamaroesGolsXSuica;
    private JTextField BrasilGolsXServia;
    private JTextField SerrviaGolsXBrasil;
    private JTextField CamaroesGolsXServia;
    private JTextField ServiaGolsXCamaroes;
    private JTextField BrasilGolsXSuica;
    private JTextField SuicaGolsXBrasil;
    private JTextField ServiaGolsXSuica;
    private JTextField SuicaGolsXServia;
    private JTextField CamaroesGolsXBrasil;
    private JTextField BrasilGolsXCamaroes;

    private JTextField[] GrupoGTexts = new JTextField[]{SuicaGolsXCamaroes, CamaroesGolsXSuica, BrasilGolsXServia, SerrviaGolsXBrasil, CamaroesGolsXServia, ServiaGolsXCamaroes, BrasilGolsXSuica, SuicaGolsXBrasil, ServiaGolsXSuica, SuicaGolsXServia, CamaroesGolsXBrasil, BrasilGolsXCamaroes};

    private JTextField UruguaiGolsXCoreia;
    private JTextField CoreiaGolsXUruguai;
    private JTextField PortugalGolsXGana;
    private JTextField GanaGolsXPortugal;
    private JTextField CoreiaGolsXGana;
    private JTextField GanaGolsXCoreia;
    private JTextField PortugalGolsXUruguai;
    private JTextField UruguaiGolsXPortugal;
    private JTextField CoreiaGolsXPortual;
    private JTextField PortugalGolsXCoreia;
    private JTextField GanaGolsXUruguai;
    private JTextField UruguaiGolsXGana;

    private JTextField[] GrupoHTexts = new JTextField[]{UruguaiGolsXCoreia, CoreiaGolsXUruguai, PortugalGolsXGana, GanaGolsXPortugal, CoreiaGolsXGana, GanaGolsXCoreia, PortugalGolsXUruguai, UruguaiGolsXPortugal, CoreiaGolsXPortual, PortugalGolsXCoreia, GanaGolsXUruguai, UruguaiGolsXGana};

    private JTextField DinamarcaGolsXTunisia;
    private JTextField TunisiaGolsXDinamarca;
    private JTextField FrancaGolsXAustralia;
    private JTextField AustraliaGolsXFranca;
    private JTextField TunisiaGolsXAustralia;
    private JTextField AustraliaGolsXTunisia;
    private JTextField FrancaGolsXDinamarca;
    private JTextField DinamarcaGolsXFranca;
    private JTextField TunisiaGolsXFranca;
    private JTextField FrancaGolsXTunisia;
    private JTextField AustraliaGolsXDinamarca;
    private JTextField DinamarcaGolsXAustralia;
    private JLabel Time1GrupoA;
    private JLabel Time2GrupoA;
    private JLabel Time3GrupoA;
    private JLabel Time4GrupoA;
    private JLabel Time1GrupoB;
    private JLabel Time2GrupoB;
    private JLabel Time3GrupoB;
    private JLabel Time4GrupoB;
    private JLabel Time1GrupoC;
    private JLabel Time2GrupoC;
    private JLabel Time3GrupoC;
    private JLabel Time4GrupoC;
    private JLabel Time1GrupoD;
    private JLabel Time2GrupoD;
    private JLabel Time3GrupoD;
    private JLabel Time4GrupoD;
    private JLabel Time1GrupoE;
    private JLabel Time2GrupoE;
    private JLabel Time3GrupoE;
    private JLabel Time4GrupoE;
    private JLabel Time1GrupoF;
    private JLabel Time2GrupoF;
    private JLabel Time3GrupoF;
    private JLabel Time4GrupoF;
    private JLabel Time1GrupoG;
    private JLabel Time2GrupoG;
    private JLabel Time3GrupoG;
    private JLabel Time4GrupoG;
    private JLabel Time1GrupoH;
    private JLabel Time2GrupoH;
    private JLabel Time3GrupoH;
    private JLabel Time4GrupoH;
    private JLabel V1A;
    private JLabel E1A;
    private JLabel D1A;
    private JLabel GP1A;
    private JLabel GC1A;
    private JLabel SG1A;
    private JLabel V2A;
    private JLabel E2A;
    private JLabel D2A;
    private JLabel GP2A;
    private JLabel GC2A;
    private JLabel SG2A;
    private JLabel V3A;
    private JLabel E3A;
    private JLabel D3A;
    private JLabel GP3A;
    private JLabel GC3A;
    private JLabel SG3A;
    private JLabel V4A;
    private JLabel E4A;
    private JLabel D4A;
    private JLabel GP4A;
    private JLabel GC4A;
    private JLabel SG4A;
    private JLabel V1B;
    private JLabel E1B;
    private JLabel D1B;
    private JLabel GP1B;
    private JLabel GC1B;
    private JLabel SG1B;
    private JLabel V2B;
    private JLabel E2B;
    private JLabel D2B;
    private JLabel GP2B;
    private JLabel GC2B;
    private JLabel SG2B;
    private JLabel V3B;
    private JLabel E3B;
    private JLabel D3B;
    private JLabel GP3B;
    private JLabel GC3B;
    private JLabel SG3B;
    private JLabel V4B;
    private JLabel E4B;
    private JLabel D4B;
    private JLabel GP4B;
    private JLabel GC4B;
    private JLabel SG4B;
    private JLabel V1C;
    private JLabel E1C;
    private JLabel D1C;
    private JLabel GP1C;
    private JLabel GC1C;
    private JLabel SG1C;
    private JLabel V2C;
    private JLabel E2C;
    private JLabel D2C;
    private JLabel GP2C;
    private JLabel GC2C;
    private JLabel SG2C;
    private JLabel V3C;
    private JLabel E3C;
    private JLabel D3C;
    private JLabel GP3C;
    private JLabel GC3C;
    private JLabel SG3C;
    private JLabel V4C;
    private JLabel E4C;
    private JLabel D4C;
    private JLabel GP4C;
    private JLabel GC4C;
    private JLabel SG4C;
    private JLabel E1D;
    private JLabel V1D;
    private JLabel D1D;
    private JLabel GP1D;
    private JLabel GC1D;
    private JLabel SG1D;
    private JLabel V2D;
    private JLabel E2D;
    private JLabel D2D;
    private JLabel GP2D;
    private JLabel GC2D;
    private JLabel SG2D;
    private JLabel V3D;
    private JLabel E3D;
    private JLabel D3D;
    private JLabel GP3D;
    private JLabel GC3D;
    private JLabel SG3D;
    private JLabel V4D;
    private JLabel E4D;
    private JLabel D4D;
    private JLabel GP4D;
    private JLabel GC4D;
    private JLabel SG4D;
    private JLabel V1E;
    private JLabel E1E;
    private JLabel D1E;
    private JLabel GP1E;
    private JLabel GC1E;
    private JLabel SG1E;
    private JLabel V2E;
    private JLabel E2E;
    private JLabel D2E;
    private JLabel GP2E;
    private JLabel GC2E;
    private JLabel SG2E;
    private JLabel V3E;
    private JLabel E3E;
    private JLabel D3E;
    private JLabel GP3E;
    private JLabel GC3E;
    private JLabel SG3E;
    private JLabel V4E;
    private JLabel E4E;
    private JLabel D4E;
    private JLabel GP4E;
    private JLabel GC4E;
    private JLabel SG4E;
    private JLabel V1F;
    private JLabel E1F;
    private JLabel D1F;
    private JLabel GP1F;
    private JLabel GC1F;
    private JLabel SG1F;
    private JLabel V2F;
    private JLabel E2F;
    private JLabel D2F;
    private JLabel GP2F;
    private JLabel GC2F;
    private JLabel SG2F;
    private JLabel V3F;
    private JLabel E3F;
    private JLabel D3F;
    private JLabel GP3F;
    private JLabel GC3F;
    private JLabel SG3F;
    private JLabel V4F;
    private JLabel E4F;
    private JLabel D4F;
    private JLabel GP4F;
    private JLabel GC4F;
    private JLabel SG4F;
    private JLabel V1G;
    private JLabel E1G;
    private JLabel D1G;
    private JLabel GP1G;
    private JLabel GC1G;
    private JLabel SG1G;
    private JLabel V2G;
    private JLabel E2G;
    private JLabel D2G;
    private JLabel GP2G;
    private JLabel GC2G;
    private JLabel SG2G;
    private JLabel V3G;
    private JLabel E3G;
    private JLabel D3G;
    private JLabel GP3G;
    private JLabel GC3G;
    private JLabel SG3G;
    private JLabel V4G;
    private JLabel E4G;
    private JLabel D4G;
    private JLabel GP4G;
    private JLabel GC4G;
    private JLabel SG4G;
    private JLabel V1H;
    private JLabel E1H;
    private JLabel D1H;
    private JLabel GP1H;
    private JLabel GC1H;
    private JLabel SG1H;
    private JLabel V2H;
    private JLabel E2H;
    private JLabel D2H;
    private JLabel GP2H;
    private JLabel GC2H;
    private JLabel SG2H;
    private JLabel V3H;
    private JLabel E3H;
    private JLabel D3H;
    private JLabel GP3H;
    private JLabel GC3H;
    private JLabel SG3H;
    private JLabel V4H;
    private JLabel E4H;
    private JLabel D4H;
    private JLabel GP4H;
    private JLabel GC4H;
    private JLabel SG4H;

    private JTextField[] GrupoDTexts = new JTextField[]{DinamarcaGolsXTunisia, TunisiaGolsXDinamarca, FrancaGolsXAustralia, AustraliaGolsXFranca, TunisiaGolsXAustralia, AustraliaGolsXTunisia, FrancaGolsXDinamarca, DinamarcaGolsXFranca, TunisiaGolsXFranca, FrancaGolsXTunisia, AustraliaGolsXDinamarca, DinamarcaGolsXAustralia};

    public static void main(String[] args) {

        JFrame frame = new JFrame("Tabela");

        frame.setContentPane(new Tabela().TabbedPanel);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.setVisible(true);

    }

}
